version: "3"

services:
  api:
    container_name: 'task-management-api'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - broker
      - db
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      DB_HOST: "db"
      DB_NAME: "db"
      DB_USERNAME: "root"
      DB_PASSWORD: "password-secret"
      DB_PORT: "3306"
      SECRET_JWT: "QKvvNE68gRt&vXNJB7Hc^Ajw"
    networks:
      - broker_net
      - db_net
  broker:
    image: rabbitmq:3-management-alpine
    container_name: 'task-management-broker'
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_PASS=password"
      - "RABBITMQ_DEFAULT_USER=username"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - broker_net
  db:
    image: mysql:5.7
    container_name: 'task-management-db'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "password-secret"
    networks:
      - db_net
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

networks:
  broker_net:
  db_net:
